services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: express-react-auth-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: express_react_auth
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express-react-auth-backend
    restart: unless-stopped
    ports:
      - "4001:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=mysql://app_user:app_password@db:3306/express_react_auth
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRES_IN=7d
      - EMAIL_PROVIDER=console
      - APP_URL=http://localhost:4001
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    command: ["npm", "run", "dev"]

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: express-react-auth-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:4001
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  mysql_data:

