services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: express-react-auth-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: express_react_auth
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis for Queue System
  redis:
    image: redis:7-alpine
    container_name: express-react-auth-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5

  # Backend Service
  # Note: Create a .env file in the backend directory using env.example as a template
  # to set your JWT_SECRET, RESEND_API_KEY, and EMAIL_FROM values
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express-react-auth-backend
    restart: unless-stopped
    ports:
      - "4001:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=mysql://app_user:app_password@db:3306/express_react_auth
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - EMAIL_PROVIDER=resend
      - RESEND_API_KEY=${RESEND_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - EMAIL_FROM=${EMAIL_FROM}
      - APP_URL=http://localhost:4001
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["npm", "run", "dev"]

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: express-react-auth-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:4001
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host"]

  # Queue Worker Service
  queue-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express-react-auth-queue-worker
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://app_user:app_password@db:3306/express_react_auth
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - EMAIL_PROVIDER=resend
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["npm", "run", "worker"]

volumes:
  mysql_data:
  redis_data:

